# Generated by Django 5.1.7 on 2026-04-16 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("province", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("municipality", models.CharField(max_length=255)),
                ("details", models.TextField()),
                ("organization_name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ongoing", "Ongoing"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("elapsed_seconds_override", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
